title: "musings.me"
author: "sid devic"
description: "tech musings and projects"
more: "read more »"
url: "http://159.203.183.245"
baseurl: ""
paginate: 4
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - about.md
  - archive.html

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/sid-devic"
  - github: "https://github.com/sid-devic"
  - envelope: "mailto:sid.devic@utd.edu"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
